title: Mother Ship的笔记
subtitle: null
description: null
keywords: null
author: Mother Ship
language: zh-CN
timezone: Asia/Shanghai
favicon: https://www.mothership.top/favicon.ico
url: http://blog.mothership.top
root: /
permalink: posts/:abbrlink.html
permalink_defaults: null
abbrlink:
  alg: crc32
  rep: hex
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 0
pagination_dir: page
theme: icarus
disqus: mother-ship
gcs: 015302745202112709039:d2rq52htkfe
deploy:
  type: git
  repository: https://github.com/Mother-Ship/Mother-Ship.github.io.git
  branch: master
location: 杭州
email: quhansheng@gmail.com
avatar: https://a.ppy.sh/2545898_.png
social:
  github: https://github.com/Mother-Ship
  weibo: null
  linkedin: null
menu:
  archives: true
  tags: true
  categories: true
